GET http://localhost:8888/hello

> {%
client.test("test-hello", function() {
  client.log("测试/hello接口！");
  client.log(response.body);
  client.log(JSON.stringify(response.body)); //虽然ides没有提示JSON，但是可以用JSON.stringify()转换成字符串
  client.assert(response.status === 200, "Response status must be 200");
  client.assert(response.body === "Hello World!", "结果验证失败");
});
%}
###


POST http://localhost:8888/hello/post
#Accept: application/json
#Content-Type: application/x-www-form-urlencoded
#> {%
#client.test("test-hello", function() {
#  client.log("测试/hello接口！");
#  client.log(response.body);
#  client.log(JSON.stringify(response.body)); //虽然ides没有提示JSON，但是可以用JSON.stringify()转换成字符串
#  client.assert(response.status === 200, "Response status must be 200");
#  client.assert(response.body === "Hello World!", "结果验证失败");
#});
#%}

name=TEST
###

GET http://localhost:8888/test/list
